<?php
namespace Yamw\Lib\Parsers;

use \Yamw\Lib\Assertions\BasicAssertions;

/**
 * Generates your constant maps for you!
 *
 * @author Anh Nhan Nguyen <anhnhan@outlook.com>
 */
class ConstantMapParser
{
    private $constantmapCode;
    private $constantmapPath;

    public function __construct($configpath = 'constant_map.php')
    {
        $this->constantmapPath = path($configpath);

        $this->constantmapCode = file_exists($this->constantmapPath) ?
        include $this->constantmapPath : array();

        BasicAssertions::assertIsArray($this->constantmapCode);
    }

    public function setEntry($name, $value)
    {
        BasicAssertions::assertIsString($name);
        BasicAssertions::assertIsString($value);

        $this->constantmapCode[$name] = $value;

        return $this;
    }

    public function save()
    {
        ob_start();
        println("<?php", false);
        println('', false);
        println("// This file has been automatically generated by ".VERSION, false);
        println("// Would be cool if you won't edit it, as that would sure break things", false);
        println('', false);
        println("return array(", false);

        foreach ($this->constantmapCode as $key => $value) {
            $key = escapeSingleQuotes($key);
            $name = escapeSingleQuotes($value);
            println("   '$key' => '$name',", false);
        }

        println(");", false);
        println('', false);
        $content = ob_get_clean();
        file_put_contents($this->constantmapPath, $content);
    }
}
