<?php

// This file has been automatically generated by Yamw v4.8
// Would be cool if you won't edit it, as that would sure break things

return array(
   'css_hash' => 'f8f78e342e0b63b6e09348b577daa45865b88037',
   'css_last_update' => '1360260211',
   'js_hash' => 'c517dfa520210d233b9aa86f90f494de79059f4f',
   'js_last_update' => '1360260220',
);

