<?php

// This file has been automatically generated by Yamw v4.8
// Would be cool if you won't edit it, as that would sure break things

return array(
   'css_hash' => 'f8f78e342e0b63b6e09348b577daa45865b88037',
   'css_last_update' => '1382822636',
   'js_hash' => '86ecefc353542f1d12a338f5229edaf1acb31027',
   'js_last_update' => '1382726119',
);

